version: '3'
services:
    php:
        image: php:7.4-fpm
        volumes:
            - ./src:/usr/share/nginx/html
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - php:7.4
        depends_on:
            - php
        networks:
            - hex-network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        networks:
            - hex-network
    mariadb:
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: hex-convert
        networks:
            - hex-network

networks:
    hex-network:
        driver: bridge
