version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./public:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - php:7.4
        networks:
            - hex-network
    php:
        build: php
        links:
            - mysql
        volumes:
            - ./public:/var/www
        networks:
            - hex-network
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./logs/mysql:/var/log/mysql
            - ./mysql/etc:/etc/mysql
            - ./mysql:/var/lib/mysql
            - ./mysql/files:/var/lib/mysql-files
            - ./mysql/data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: hex-convert
        networks:
            - hex-network

networks:
    hex-network:
        driver: bridge
